"""Shared demo datasets for all MCP servers.

Comprehensive demo data showing cross-system traceability between
JAMA requirements, Azure DevOps work items, and IcePanel components.
"""

# JAMA Requirements Demo Data
DEMO_REQUIREMENTS = [
    {
        "id": "REQ-001",
        "title": "User Authentication System",
        "description": "The system shall provide secure user authentication using multi-factor authentication (MFA) with support for OAuth 2.0, SAML, and enterprise SSO providers.",
        "status": "approved",
        "priority": "high",
        "category": "Security",
        "related": [
            {"id": "1", "type": "work_item", "system": "ADO", "title": "POC Epic: Agent with MCP Tools"},
            {"id": "2", "type": "work_item", "system": "ADO", "title": "POC Epic: Cloud Data Layer"},
            {"id": "7", "type": "work_item", "system": "ADO", "title": "POC Task 1.1: Create agent with local tools"},
            {"id": "15", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Authentication fails after token refresh"},
            {"id": "COMP-201", "type": "component", "system": "IcePanel", "title": "Authentication Service"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-001",
    },
    {
        "id": "REQ-002",
        "title": "Data Encryption at Rest",
        "description": "All sensitive data including user credentials, personal information, and financial records shall be encrypted at rest using AES-256 encryption with Azure Key Vault integration.",
        "status": "approved",
        "priority": "critical",
        "category": "Security",
        "related": [
            {"id": "8", "type": "work_item", "system": "ADO", "title": "POC Task 1.2: Add MCP client integration"},
            {"id": "13", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Timeout on MCP tool calls"},
            {"id": "16", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Memory leak in MCP client connection pool"},
            {"id": "COMP-202", "type": "component", "system": "IcePanel", "title": "Encryption Module"},
            {"id": "COMP-206", "type": "component", "system": "IcePanel", "title": "Data Storage Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-002",
    },
    {
        "id": "REQ-003",
        "title": "Audit Logging & Traceability",
        "description": "The system shall maintain comprehensive audit logs for all user actions, administrative operations, and data access. Logs must be tamper-proof and retained for 7 years per compliance requirements.",
        "status": "approved",
        "priority": "high",
        "category": "Compliance",
        "related": [
            {"id": "9", "type": "work_item", "system": "ADO", "title": "POC Task 1.3: Test work item retrieval performance"},
            {"id": "10", "type": "work_item", "system": "ADO", "title": "POC Task 2.1: Integrate with VS Code Copilot"},
            {"id": "11", "type": "work_item", "system": "ADO", "title": "POC Task 2.2: Deploy MCP servers to Azure"},
            {"id": "COMP-203", "type": "component", "system": "IcePanel", "title": "Audit Log Service"},
            {"id": "COMP-209", "type": "component", "system": "IcePanel", "title": "Message Queue"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-003",
    },
    {
        "id": "REQ-004",
        "title": "API Performance & Scalability",
        "description": "The system shall handle 10,000 concurrent users with API response times under 200ms for 95th percentile. The architecture must support horizontal scaling and auto-scaling based on load.",
        "status": "approved",
        "priority": "high",
        "category": "Performance",
        "related": [
            {"id": "12", "type": "work_item", "system": "ADO", "title": "POC Task 3.1: Configure monitoring"},
            {"id": "13", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Timeout on MCP tool calls"},
            {"id": "14", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Response times degraded after 1000 requests"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
            {"id": "COMP-205", "type": "component", "system": "IcePanel", "title": "Load Balancer"},
            {"id": "COMP-210", "type": "component", "system": "IcePanel", "title": "Cache Layer"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-004",
    },
    {
        "id": "REQ-005",
        "title": "Data Backup & Recovery",
        "description": "The system shall perform automated daily backups with point-in-time recovery capability. Recovery Time Objective (RTO) must be under 4 hours and Recovery Point Objective (RPO) under 1 hour.",
        "status": "approved",
        "priority": "critical",
        "category": "Reliability",
        "related": [
            {"id": "3", "type": "work_item", "system": "ADO", "title": "POC Task: Create demo datasets"},
            {"id": "17", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Backup job fails with large datasets"},
            {"id": "COMP-206", "type": "component", "system": "IcePanel", "title": "Data Storage Service"},
            {"id": "COMP-211", "type": "component", "system": "IcePanel", "title": "Backup Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-005",
    },
    {
        "id": "REQ-006",
        "title": "Real-time Notifications",
        "description": "The system shall provide real-time notifications to users for critical events including security alerts, system status changes, and workflow approvals using WebSocket connections.",
        "status": "approved",
        "priority": "medium",
        "category": "Integration",
        "related": [
            {"id": "4", "type": "work_item", "system": "ADO", "title": "POC Task: Setup Azure Functions"},
            {"id": "18", "type": "work_item", "system": "ADO", "title": "POC Bug Task: WebSocket connections drop after 5 minutes"},
            {"id": "COMP-207", "type": "component", "system": "IcePanel", "title": "Notification Service"},
            {"id": "COMP-208", "type": "component", "system": "IcePanel", "title": "WebSocket Handler"},
            {"id": "COMP-209", "type": "component", "system": "IcePanel", "title": "Message Queue"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-006",
    },
    {
        "id": "REQ-007",
        "title": "API Rate Limiting & Throttling",
        "description": "The system shall implement rate limiting of 1000 requests per minute per client IP address to prevent abuse and ensure fair resource allocation. Premium tier users shall receive 5000 requests per minute.",
        "status": "approved",
        "priority": "high",
        "category": "Security",
        "related": [
            {"id": "5", "type": "work_item", "system": "ADO", "title": "POC Task: Create README documentation"},
            {"id": "14", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Response times degraded after 1000 requests"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
            {"id": "COMP-210", "type": "component", "system": "IcePanel", "title": "Cache Layer"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-007",
    },
    {
        "id": "REQ-008",
        "title": "User Interface Accessibility",
        "description": "The system UI shall comply with WCAG 2.1 Level AA accessibility standards including keyboard navigation, screen reader support, and high contrast modes for visually impaired users.",
        "status": "draft",
        "priority": "medium",
        "category": "Usability",
        "related": [
            {"id": "6", "type": "work_item", "system": "ADO", "title": "POC Task: Test UI components"},
            {"id": "COMP-212", "type": "component", "system": "IcePanel", "title": "Web Frontend"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/jama/REQ-008",
    },
]

# Azure DevOps Work Items Demo Data
DEMO_WORK_ITEMS = [
    {
        "id": "WI-101",
        "type": "User Story",
        "title": "Implement OAuth 2.0 authentication flow",
        "description": "As a user, I want to log in using OAuth 2.0 providers (Google, Microsoft, GitHub)",
        "state": "Active",
        "assigned_to": "Jane Smith",
        "related_ids": ["REQ-001", "TEST-301", "COMP-201"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-101",
    },
    {
        "id": "WI-102",
        "type": "Task",
        "title": "Configure Azure Key Vault for encryption keys",
        "description": "Set up Key Vault to manage encryption keys securely",
        "state": "Completed",
        "assigned_to": "John Doe",
        "related_ids": ["REQ-002", "COMP-202"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-102",
    },
    {
        "id": "WI-103",
        "type": "Bug",
        "title": "Audit logs missing timestamp field",
        "description": "Discovered that audit log entries don't include UTC timestamps",
        "state": "New",
        "assigned_to": "Alice Johnson",
        "related_ids": ["REQ-003", "COMP-203"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-103",
    },
    {
        "id": "WI-104",
        "type": "User Story",
        "title": "Multi-factor authentication support",
        "description": "As a security admin, I want to enforce MFA for all users to enhance account security",
        "state": "Active",
        "assigned_to": "Jane Smith",
        "related_ids": ["REQ-001", "COMP-201"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-104",
    },
    {
        "id": "WI-105",
        "type": "Task",
        "title": "Implement session timeout mechanism",
        "description": "Add automatic session expiration after 30 minutes of inactivity",
        "state": "Active",
        "assigned_to": "Jane Smith",
        "related_ids": ["REQ-001", "COMP-201"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-105",
    },
    {
        "id": "WI-106",
        "type": "Task",
        "title": "Create encryption performance benchmarks",
        "description": "Measure and document encryption/decryption performance across different data sizes",
        "state": "In Progress",
        "assigned_to": "John Doe",
        "related_ids": ["REQ-002", "COMP-202"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-106",
    },
    {
        "id": "WI-107",
        "type": "Bug",
        "title": "Key rotation fails in production",
        "description": "Azure Key Vault key rotation is throwing timeout errors in production environment",
        "state": "Active",
        "assigned_to": "John Doe",
        "related_ids": ["REQ-002", "COMP-202"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-107",
    },
    {
        "id": "WI-108",
        "type": "User Story",
        "title": "Audit log export functionality",
        "description": "As a compliance officer, I want to export audit logs to CSV for regulatory reporting",
        "state": "New",
        "assigned_to": "Alice Johnson",
        "related_ids": ["REQ-003", "COMP-203"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-108",
    },
    {
        "id": "WI-109",
        "type": "Task",
        "title": "Add log retention policy enforcement",
        "description": "Implement automatic deletion of logs older than 7 years per compliance requirements",
        "state": "Active",
        "assigned_to": "Alice Johnson",
        "related_ids": ["REQ-003", "COMP-203"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-109",
    },
    {
        "id": "WI-110",
        "type": "Task",
        "title": "Setup API Gateway rate limiting",
        "description": "Configure rate limiting rules to prevent DDoS attacks (1000 req/min per IP)",
        "state": "Completed",
        "assigned_to": "Mike Chen",
        "related_ids": ["COMP-204"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-110",
    },
    {
        "id": "WI-111",
        "type": "Bug",
        "title": "API Gateway returns 502 under high load",
        "description": "Gateway crashes when handling more than 5000 concurrent requests",
        "state": "Active",
        "assigned_to": "Mike Chen",
        "related_ids": ["COMP-204"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-111",
    },
    {
        "id": "WI-112",
        "type": "User Story",
        "title": "Password complexity requirements",
        "description": "As a security admin, I want to enforce strong password policies (min 12 chars, special chars, etc.)",
        "state": "Active",
        "assigned_to": "Jane Smith",
        "related_ids": ["REQ-001", "COMP-201"],
        "deeplink_url": "https://demo-viewer.example.com/ado/WI-112",
    },
]

# IcePanel Architecture Components Demo Data
DEMO_COMPONENTS = [
    {
        "id": "COMP-201",
        "name": "Authentication Service",
        "type": "Microservice",
        "description": "Handles user authentication and token management using OAuth 2.0, SAML, and MFA. Integrates with Azure AD and external identity providers.",
        "technology": "Node.js + Passport.js + Redis",
        "layer": "Application",
        "related": [
            {"id": "REQ-001", "type": "requirement", "system": "JAMA", "title": "User Authentication System"},
            {"id": "1", "type": "work_item", "system": "ADO", "title": "POC Epic: Agent with MCP Tools"},
            {"id": "7", "type": "work_item", "system": "ADO", "title": "POC Task 1.1: Create agent with local tools"},
            {"id": "15", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Authentication fails after token refresh"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-201",
    },
    {
        "id": "COMP-202",
        "name": "Encryption Module",
        "type": "Library",
        "description": "Provides encryption/decryption utilities using Azure Key Vault with AES-256 encryption. Handles key rotation and certificate management.",
        "technology": "Python + Azure Key Vault SDK",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-002", "type": "requirement", "system": "JAMA", "title": "Data Encryption at Rest"},
            {"id": "8", "type": "work_item", "system": "ADO", "title": "POC Task 1.2: Add MCP client integration"},
            {"id": "13", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Timeout on MCP tool calls"},
            {"id": "16", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Memory leak in MCP client connection pool"},
            {"id": "COMP-206", "type": "component", "system": "IcePanel", "title": "Data Storage Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-202",
    },
    {
        "id": "COMP-203",
        "name": "Audit Log Service",
        "type": "Microservice",
        "description": "Centralized logging service for audit trail and compliance reporting. Provides tamper-proof logs with cryptographic signatures and 7-year retention.",
        "technology": "Go + PostgreSQL + TimescaleDB",
        "layer": "Application",
        "related": [
            {"id": "REQ-003", "type": "requirement", "system": "JAMA", "title": "Audit Logging & Traceability"},
            {"id": "9", "type": "work_item", "system": "ADO", "title": "POC Task 1.3: Test work item retrieval performance"},
            {"id": "10", "type": "work_item", "system": "ADO", "title": "POC Task 2.1: Integrate with VS Code Copilot"},
            {"id": "11", "type": "work_item", "system": "ADO", "title": "POC Task 2.2: Deploy MCP servers to Azure"},
            {"id": "COMP-209", "type": "component", "system": "IcePanel", "title": "Message Queue"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-203",
    },
    {
        "id": "COMP-204",
        "name": "API Gateway",
        "type": "Gateway",
        "description": "Entry point for all client requests with intelligent routing, rate limiting, request transformation, and API versioning support.",
        "technology": "Kong + Nginx",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-004", "type": "requirement", "system": "JAMA", "title": "API Performance & Scalability"},
            {"id": "REQ-007", "type": "requirement", "system": "JAMA", "title": "API Rate Limiting & Throttling"},
            {"id": "12", "type": "work_item", "system": "ADO", "title": "POC Task 3.1: Configure monitoring"},
            {"id": "14", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Response times degraded after 1000 requests"},
            {"id": "COMP-201", "type": "component", "system": "IcePanel", "title": "Authentication Service"},
            {"id": "COMP-205", "type": "component", "system": "IcePanel", "title": "Load Balancer"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-204",
    },
    {
        "id": "COMP-205",
        "name": "Load Balancer",
        "type": "Infrastructure",
        "description": "Distributes incoming traffic across multiple API Gateway instances with health checks, auto-scaling, and failover capabilities.",
        "technology": "Azure Application Gateway",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-004", "type": "requirement", "system": "JAMA", "title": "API Performance & Scalability"},
            {"id": "12", "type": "work_item", "system": "ADO", "title": "POC Task 3.1: Configure monitoring"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-205",
    },
    {
        "id": "COMP-206",
        "name": "Data Storage Service",
        "type": "Microservice",
        "description": "Primary data persistence layer with support for transactional operations, partitioning, and replication across multiple regions.",
        "technology": "Azure Cosmos DB + PostgreSQL",
        "layer": "Data",
        "related": [
            {"id": "REQ-002", "type": "requirement", "system": "JAMA", "title": "Data Encryption at Rest"},
            {"id": "REQ-005", "type": "requirement", "system": "JAMA", "title": "Data Backup & Recovery"},
            {"id": "3", "type": "work_item", "system": "ADO", "title": "POC Task: Create demo datasets"},
            {"id": "17", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Backup job fails with large datasets"},
            {"id": "COMP-202", "type": "component", "system": "IcePanel", "title": "Encryption Module"},
            {"id": "COMP-211", "type": "component", "system": "IcePanel", "title": "Backup Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-206",
    },
    {
        "id": "COMP-207",
        "name": "Notification Service",
        "type": "Microservice",
        "description": "Multi-channel notification delivery supporting email, SMS, push notifications, and in-app alerts with templating and scheduling.",
        "technology": "Python + SendGrid + Twilio",
        "layer": "Application",
        "related": [
            {"id": "REQ-006", "type": "requirement", "system": "JAMA", "title": "Real-time Notifications"},
            {"id": "4", "type": "work_item", "system": "ADO", "title": "POC Task: Setup Azure Functions"},
            {"id": "COMP-208", "type": "component", "system": "IcePanel", "title": "WebSocket Handler"},
            {"id": "COMP-209", "type": "component", "system": "IcePanel", "title": "Message Queue"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-207",
    },
    {
        "id": "COMP-208",
        "name": "WebSocket Handler",
        "type": "Microservice",
        "description": "Manages persistent WebSocket connections for real-time bidirectional communication with automatic reconnection and message buffering.",
        "technology": "Node.js + Socket.IO + Redis",
        "layer": "Application",
        "related": [
            {"id": "REQ-006", "type": "requirement", "system": "JAMA", "title": "Real-time Notifications"},
            {"id": "18", "type": "work_item", "system": "ADO", "title": "POC Bug Task: WebSocket connections drop after 5 minutes"},
            {"id": "COMP-207", "type": "component", "system": "IcePanel", "title": "Notification Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-208",
    },
    {
        "id": "COMP-209",
        "name": "Message Queue",
        "type": "Infrastructure",
        "description": "Asynchronous message broker for decoupling services and ensuring reliable event delivery with dead-letter queues and retry logic.",
        "technology": "Azure Service Bus",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-003", "type": "requirement", "system": "JAMA", "title": "Audit Logging & Traceability"},
            {"id": "REQ-006", "type": "requirement", "system": "JAMA", "title": "Real-time Notifications"},
            {"id": "COMP-203", "type": "component", "system": "IcePanel", "title": "Audit Log Service"},
            {"id": "COMP-207", "type": "component", "system": "IcePanel", "title": "Notification Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-209",
    },
    {
        "id": "COMP-210",
        "name": "Cache Layer",
        "type": "Infrastructure",
        "description": "Distributed caching layer for improving API response times and reducing database load with TTL-based expiration and cache warming.",
        "technology": "Redis Cluster",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-004", "type": "requirement", "system": "JAMA", "title": "API Performance & Scalability"},
            {"id": "REQ-007", "type": "requirement", "system": "JAMA", "title": "API Rate Limiting & Throttling"},
            {"id": "13", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Timeout on MCP tool calls"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-210",
    },
    {
        "id": "COMP-211",
        "name": "Backup Service",
        "type": "Microservice",
        "description": "Automated backup orchestration with point-in-time recovery, incremental backups, and geo-redundant storage for disaster recovery.",
        "technology": "Azure Backup + Python",
        "layer": "Infrastructure",
        "related": [
            {"id": "REQ-005", "type": "requirement", "system": "JAMA", "title": "Data Backup & Recovery"},
            {"id": "17", "type": "work_item", "system": "ADO", "title": "POC Bug Task: Backup job fails with large datasets"},
            {"id": "COMP-206", "type": "component", "system": "IcePanel", "title": "Data Storage Service"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-211",
    },
    {
        "id": "COMP-212",
        "name": "Web Frontend",
        "type": "UI",
        "description": "Single-page application (SPA) providing responsive UI with WCAG 2.1 Level AA accessibility compliance and progressive web app (PWA) capabilities.",
        "technology": "React + TypeScript + Material-UI",
        "layer": "Presentation",
        "related": [
            {"id": "REQ-008", "type": "requirement", "system": "JAMA", "title": "User Interface Accessibility"},
            {"id": "6", "type": "work_item", "system": "ADO", "title": "POC Task: Test UI components"},
            {"id": "COMP-204", "type": "component", "system": "IcePanel", "title": "API Gateway"},
        ],
        "deeplink_url": "https://demo-viewer.example.com/icepanel/COMP-212",
    },
]

# Test Cases Demo Data
DEMO_TESTS = [
    {
        "id": "TEST-301",
        "title": "Verify OAuth login with Google provider",
        "description": "Test successful authentication using Google OAuth",
        "status": "passed",
        "related_ids": ["WI-101", "REQ-001"],
        "deeplink_url": "https://demo-viewer.example.com/tests/TEST-301",
    },
]
